baseurl = "https://abrahamraji.in/"
title = "Abraham Raji | Software Developer • Human"
languageCode = "en-us"
paginate = "10" # Number of posts per page

#-------------------------------------------------------------------------------
# DEFAULT SETTINGS
#-------------------------------------------------------------------------------

# Default Theme
theme= "gruvhugo"

# Default Post Extension
defaultExtension= "html"

# Default metadata format for newly created frontmatter using
# hugo new command. "toml", "yaml", or "json"
metaDataFormat= "yaml"

[taxonomies]
  tag      = "tags"
  category = "categories"
  series   = "series"

[params.main]
  enabled = true
  enableKatex= false
  headerTitle = "אַבְרָהָם"
  copyright = "<p>Made with <span style=\"font-size: 20px; color: #e25555;\">♥</span> in GNU Emacs. All original content is licensed under a free/libre <a class= \"link\" href='{{ .Site.Params.main.licenseUrl }}'>copyleft</a> license.</p>"
  img = "img/abraham.jpg"
  icon = "img/man.png"
  quote = "Mea navis aëricumbens anguillis abundat."
  description= "My name is Abraham Raji. I'm a maker. I design and build solutions to problems that fascinate me. I believe in sensible and intuitive design that is beautiful both on the outside as well as under the hood."
  licenseUrl = "https://gitlab.com/avron/avron.gitlab.io/-/raw/master/LICENSE"
 # Social icons
  [[params.social]]
    name = "gitlab"
    url  = "https://gitlab.com/avron"

  [[params.social]]
    name = "email"
    url  = "mailto:avronr@tuta.io"

  [[params.social]]
    name = "mastodon"
    url  = "https://aana.site/@avronr"

  [[params.social]]
    name = "matrix"
    url  = "https://matrix.to/#/@abraham_raji:matrix.org"

  [[params.social]]
    name = "gpg"
    url  = "https://keys.openpgp.org/vks/v1/by-fingerprint/97D54A9F8F5058547B526937AD8179A470ECF312"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/avronr"

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"

  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "post/"

  [[menu.main]]
    identifier = "wiki"
    name       = "Wiki"
    url        = "https://wiki.abrahamraji.in"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1
