baseurl = "https://abrahamraji.in/"
title = "Abraham Raji | Software Developer • Human"
languageCode = "en-us"
paginate = "10" # Number of posts per page

#-------------------------------------------------------------------------------
# DEFAULT SETTINGS
#-------------------------------------------------------------------------------

# Default Theme
theme= "gruvhugo"

# Default Post Extension
defaultExtension= "html"

# Default metadata format for newly created frontmatter using
# hugo new command. "toml", "yaml", or "json"
metaDataFormat= "yaml"

[taxonomies]
  tag      = "tags"
  category = "categories"
  series   = "series"

[params.main]
  enabled = true
  enableKatex= false
  headerTitle = "אַבְרָהָם"
  copyright = "<p>Made with <span style=\"font-size: 20px; color: #e25555;\">♥</span> in <a href=\"https://www.gnu.org/software/emacs/\">GNU Emacs</a>. All original content is licensed under a free/libre <a class= \"link\" href='{{ .Site.Params.main.licenseUrl }}'>copyleft</a> license.</p>"
  img = "img/abraham.jpg"
  icon = "img/man.png"
  quote = "Mea navis aëricumbens anguillis abundat."
  description= "This website belongs to Abraham Raji who is mostly figuring things out about him and the world around him. He is a minimalist who among other things likes good engineering and coincidently he happens to be an engineer by trade and passion. Other things he likes include good art, good conversations and good food."
  licenseUrl = "https://gitlab.com/avron/avron.gitlab.io/-/raw/master/LICENSE"

# Social icons
  [[params.social]]
    name = "gitlab"
    url  = "https://gitlab.com/avron"

  [[params.social]]
    name = "email"
    url  = "mailto:avronr@tuta.io"

  [[params.social]]
    name = "mastodon"
    url  = "https://aana.site/@avronr"

  [[params.social]]
    name = "matrix"
    url  = "https://matrix.to/#/@abraham_raji:matrix.org"

  [[params.social]]
    name = "gpg"
    url  = "https://keys.openpgp.org/vks/v1/by-fingerprint/97D54A9F8F5058547B526937AD8179A470ECF312"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/avronr"

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"

  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "post/"

  [[menu.main]]
    identifier = "wiki"
    name       = "Wiki"
    url        = "https://wiki.abrahamraji.in"


[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
