baseurl = "https://abrahamraji.in/"
title = "Abraham Raji"
languageCode = "en-us"
paginate = "10" # Number of posts per page
#disqusShortname = "" # Enable comments by entering your Disqus shortname
#googleAnalytics = "" # Enable Google Analytics by entering your tracking id
#-------------------------------------------------------------------------------
# DEFAULT SETTINGS
#-------------------------------------------------------------------------------

# Default Theme
theme= "gruvhugo"

# Default Post Extension
defaultExtension= "html"

# Default metadata format for newly created frontmatter using
# hugo new command. "toml", "yaml", or "json"
metaDataFormat= "yaml"

[taxonomies]
  tag      = "tags"
  category = "categories"
  series   = "series"

[params.main]
  enabled = true
  img = "img/abraham.jpg"
  icon = "img/man.png"
  description= "My name is Abraham Raji. I'm a maker. I design and build solutions to problems that fascinate me. I consider myself a minimalist who believes in sensible and intuitive design that is beautiful both on the outside as well as under the hood."

 # Social icons
  [[params.social]]
    name = "gitlab"
    url  = "https://gitlab.com/avron"

  [[params.social]]
    name = "email"
    url  = "mailto:avronr@tuta.io"

  [[params.social]]
    name = "mastodon"
    url  = "https://aana.site/@avronr"

  [[params.social]]
    name = "matrix"
    url  = "https://matrix.to/#/@abraham_raji:matrix.org"

  [[params.social]]
    name = "gpg"
    url  = "https://keys.openpgp.org/search?q=avronr@tuta.io"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/avronr"

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"

  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts/"

  [[menu.main]]
    identifier = "wiki"
    name       = "Wiki"
    url        = "https://wiki.abrahamraji.in"
