image: "debian:unstable"

before_script:
  - apt-get update -y
  - apt-get install -y git hugo

stages:
  - build

build-branch:
  stage: build
  script:
  - hugo new site test && cd test
    - mkdir themes/gruvhugo 
    - cp -r ../archetypes themes/gruvhugo
    - cp -r ../exampleSite themes/gruvhugo 
    - cp -r ../layouts themes/gruvhugo
    - cp ../LICENSE themes/gruvhugo
    - cp ../README.md themes/gruvhugo
    - cp -r ../static themes/gruvhugo
    - cp ../theme.toml themes/gruvhugo
    - rm -rf ../content && cp -r themes/gruvhugo/exampleSite/content/ . 
    - rm config.toml && cp themes/gruvhugo/exampleSite/deploy.toml ./config.toml 
    - hugo
    
build-tag:
  stage: build
  script:
    - make ttf webfonts
    - sh tools/artifacts.sh
  artifacts:
    paths:
    - build/
  only:
    - tags

test:
  stage: test
  before_script:
    - apt-get update -y
    - apt-get install -y make libharfbuzz-bin
  script:
    - make test


release:
  stage: release
  trigger: smc/smc.org.in
  only:
    - tags
