#+TITLE: About
#+DATE: 2020-06-13T17:13:37+05:30

* Hey 👋

- My name is Abraham Raji. I am known online as =avronr=[fn:1]  [fn:2].
- I write software for a living.
- I’m a GNU/Linux user, mainly Debian GNU/Linux[fn:3]. I no longer use or need
  Microsoft® Windows® but I have to use macOS at work (even though I don’t
  really like macOS or Apple in general).
- I primarily do most of my work in [[https://gnu.org/software/emacs/][GNU Emacs]] which is one of the greatest piece
  of software ever written with respect to what it enables it's users to do. Do 
  feel free to reach out regarding anything related to Emacs.
- I like programming languages and operating systems.
- Apart from programming I like knowing random stuff that interests me, trying
  new things, making things, consuming art and having good conversation with
  sane people.

* Disclaimer about this site and blog.
 Opinions stated here are my own and do not express the views of my employer,
 pets, neighbors, favorite authors, or anyone else who is not  me. And maybe
 not even me, depending on how old the page is.

* Contact

- **Mastodon**: [[https://aana.site/@avronr][@avronr]]
- **Twitter**: [[https://twitter.com/avron_raji][@avron_raji]]
- **Github**: [[https://github.com/abrahamparayil][@abrahamparayil]]
- **GitLab**: [[https://githhub.com/avron][@avron]]
- **Diaspora**: [[https://poddery.com/people/d69a8ff0103b01375da0002168e35aba][@avronr]]

[fn:1] This name was never intended to be used in person, infact it
was never intended to be physically pronounced even. This name is intended for
use on the web only. If I am physically close to you and you wish to address me
just use Abraham.
[fn:2] The name =avronr= consists of two parts, =avron= which is a Hebrew
version of Abraham (and I'm told it's the same in Greek too) and =r= which
should be easy to guess from my real name.
[fn:3] [[https://abrahamraji.in/post/debian/][Why Debian?]]
