#+TITLE: How the Future will remember Us
#+date: 2021-02-27T20:33:06+05:30
#+tags[]: thoughts future
#+draft: false

* Back in the good old days
This is a phrase that we hear a lot from old timers. **Most** of the
observations that follow this phrase in my experience tend to belong to one or
more of the following categories:
1. ignorant
2. misinformed
3. Discriminatory (racist, sexist, homophobic etc.)
4. for the lack of a better word, kinda stupid.
These are often arguments along the lines of joint families are better than
nuclear families, we would all be better of without technology, everyone used to
be healthier in general back in the old days etc. Their generation can't seem to
see where they're wrong and they seem to justify their views at whatever cost.
However we on the other hand can see where they're wrong, that the size of the
family doesn't have any corelation to how healthy the family is, that technology
is neither good nor evil and the real issue is the human creators of the
technology, how life expectancy around the world has increased in the past few
years etc. The point I'm trying to make is we see where they're wrong and they
probably where able to see where their previous generation went wrong too but
not their own. Now here's the billion dollar question, are we like them?

Right now are we able to see where we are going? Are we able to see what we're
doing wrong? How will the future remember us?

Of course one could argue in the grand scheme of things the future generations
wouldn't find us any different from the generations before us or after us, that
compared to the technology and tools available to them, our supercomputers and
the tools from stone age might not look too different to them. But just in case
that's not the case these are the few things that I think the future will
remember us for.

* Things we will be remembered for:
** Scientific Advancements
We will be remembered as a generation that pushed the boundaries of
scientific innovations like no other until our time, a generation that was
close to truth like no other up until our time but sadly some if not most of
us were not that great at accepting those truths when we didn't like them. We
still divided our societies based on stories that were taught as truth, we
still gave ourselves into superstitions, we still invested more money into
religion than feeding the hungry, we still did things that were wrong simply
because someone wrote it somewhere a long time ago and called it the divine
will and we always turned to the one above to save the world when we were the
ones who were suppose to save it. We will be remembered as the generation
that still killed each other in the name of religion despite their
scientific advancements.
** Learning from history
We will be remembered as the offspring of a generation that saw the
atrocities of centralized power (dictators, kings, facist nations etc.) who
then taught our generation why that is bad so that we wouldn't let that happen
again. There might have been schools of thoughts in various places in
different eras that talked against centralized power but never was it thought
to almost every child in a generation of humans but us. Yet when centralized
power came in front of us in form of corporates we did what our previous
generations did, roll over and sing praise. No matter how these corporates
took away our rights such as freedom and privacy (whether as an employee or
as a user of a service or a product) we still sang their praise. We set them
as our scales of success. No matter how many communities they destroyed, no
matter how many lives they took we still sang their praise and saw their
leaders as Gods on Earth that deserved to be worshiped, when all these people
cared about was their profit margin.

**We made it okay to put profit over people.**
** Giving everyone a voice
We will be remembered as a generation which gave almost every human on the
planet a platform that would let them have their voice heard. It was no
longer easy to silence people. People were able to organize themselves like
never before for causes that mattered. We will also be remembered as the
generation that (even though they had such platforms) were reluctant to have
an opinion or be vocal about them because it might displease the corporate
overlords and affect the amount of money they make. In a society that
revolved around money that really helped shut a lot of people up. We will
also be remembered as the generation that was a victim of surveillance like
no other and for the first time ever, victims of targetted misinformation
powered by artificial intelligence deployed by the platforms that we so
dearly loved so that they could profit from the spike in usage caused by
conflicts from misinformation. We also learned to live with this pretty well.
** Democracy
We will be remembered as a generation that enjoyed the fruits of democracy
like no other generation up until our time. Most countries were democratic,
political power was distributed and people had a say in their future. We
would also be remembered as the generation that probably failed democracy.
We blindly followed figures who played saviours without questioning what
we were asked to raise our voice for. We let the elected representatives do
things that were against the very spirit of democracy and let them get away
with it. We failed to call on them when we saw that their loyalty changed
from people to profit. We let things happen as we were busy making money.

It seems that it is possible for us nowadays to justify any cost (human rights,
human lives, environment) as long as it brings back monetary profit. If we
continue on this path we will be remembered as the generation that almost
got there but lost it all in the name of money.
