#+TITLE: Jared Leto's Joker
#+date: 2020-08-17T03:56:37+05:30
#+tags[]: pop-culture DC joker

*** Am I the only person who liked the direction in which they were taking the Joker's Charcter with Jared Leto?

Cesar Romero's Joker was well literally a joker that pulled pranks on Batman.

Jack Nicholson's Joker was dark, psychotic and driven by revenge.

Joker from the animated series IMO was written around Batman and being his arch nemesis. It can be compared to kind of connection between Batman and Joker in the Dark Knight series.

Joker in the Dark Knight Rises was centered around his idea of world and how he tries to prove it. He tries to abolish the self righteousness in people as they only do what's right when it's convenient for them. Batman was a direct contradiction to this idea so he became Joker's arch nemesis.

Joker by Pheonix bought out a new aspect where we see him turn. An origin. This time no toxic chemicals just society. Here the primary difference is that the joker doesn't speak for himself he spoke everyone who had to suffer because of the greed of the upperclass. This is who people follow him. In other Joker's it's not made clear why the people who follow him follow him.

Now,

For all the above Joker's their biggest strength was their immunity. He had nothing to loose. Well you could argue the only thing he could loose was well... Batman.

But Jared Leto's Joker wasn't that. He cared about Harley Quin. He was insane, he was driven by ideas. But he also had things he cared for in life. A more humane Joker. That to me is something new. That is something I believe must be explored. It's like the idea of a Superman that bleeds.

It's a direction worth exploring. I personally believe Jared Leto was not given a a proper chance at this.

I believe DC cinematic universe is right now chasing Marvel's success and trying to give the audience what they want. This is why they're pushing back Leto's Joker and not doing the same with Robbie's Harley Quinn.

Why do people hate Leto's Joker?
1. There's a crowd that were comparing it to Heath Ledger's portrayal of the joker without realising that they're not the same. People who are only familiar with the character through the movies and maybe a YouTube video or two.

2. There's an elitist crowd that is blinded by the bad implementation of Suicide Squad and fails to the see the potential of the character.

3. People who can't accept anything new?

Well there you go these are my thoughts. Tell me why I'm wrong, tell me why I'm right and hopefully we can have a wonderful conversation.
