#+TITLE: Waiting for Halley
#+DATE: 2021-08-04T23:17:38+05:30
#+TAGS[]: life astronomy
#+DRAFT: false

I've never really been an amateur astronomer but I've always loved looking at
the night sky. I've always struggled with the idea that we may be alone here.
Like the universe is huge, about ninety billion light years wide [fn:1] and the
earth is about 12 thousand kilometers wide. To put that in perspective consider
these:
- A photon takes about 8 minutes or about 0.00002 years to reach the earth from the sun.
- A bullet on the other hand would take 17 years.
- It will take the Voyager about 80,000-90,000 years to reach the closest star cluster.
- A photon would take more than 90,000,000,000 years to travel from one end of the
  universe to the other.

Now in the age of Jeff Bezoz and Bill Gates a thousand, a million and a billion
may not seem that far apart. But if you started counting now one second at a time, a
thousand seconds would not even make an hour, but now a million seconds is about
12 days and get ready for this a billion seconds is 32... years. Now read the
four statements above again and just let all that sink in. Ladies and Gentlemen
we are nothing but a spec of dust in the entire universe and by us I mean our
planet that holds all of us. The idea that in this entire universe this little
spec of dust is the only to hold any form of thought or intelligence is
unsettling to say the least.

What I feel is the opposite claustrophobia and a weird sense of loneliness when
I think of myself as a living sentient being. It is true that you and I or our
actions or our joys and sorrows will not matter in the grand picture. We may
not even be the first or the last sentient beings in the universe. I do not
think that we were accidents though and you shouldn't either regardless of
whether you believe in God or not. If you believe in God you already believe in
the inherent superiorly of human race which is in all honesty a dumb idea. If
you don't believe in God it means that everything in the world came into
existence as reaction which in itself doesn't have anything accidental about it,
you mix A and B you get C that's just the way universe is, we are a state in an
on-going reaction at the scale of the universe. Either way we're not accidents.
We're a possibility that came into existence which makes me think of all the
different possibilities that had to be eliminated for me to exist. Every second
in our lives is a unique link created at that exact moment from the sea of
possibilities that could have been.

You can't help but feel a little special. Not because of any inherent merit of
who you are but simply because you are. We are here and alive, watching yet
another night sky as the stars burn and black holes gluttonously consume,
witnessing this single moment in time as a sentient being able to witness,
perceive and feel it's beauty.

I am grateful for being alive and to be alive with others that I can love and
have a sense of belonging with, to whom my life and decisions I take matter
without whom even the most beautiful of the symphonies, the most awe inspiring
painting and every ground breaking discovery I make would go unnoticed and
unappreciated. Completely pointless. I am worried about the how lonely we humans
may be but at the same time I am also grateful for having other humans that add
meaning to my life.

We may in fact be alone in the universe at least for now but that doesn't mean
we don't have visitors. Halley's Comet is one such visitor. Halley's Comet looks
like what you might call a shooting star and comes to visit us once every 75–76
years. Which means if someone gets lucky enough it's possible to see Halley's
Comet twice in a single lifetime. In fact Halley's comet is the only comet with
this property. Unfortunately I won't be able to witness the Halley's Comet
twice. I am jealous of the generation that gets to. Imagine comparing life and
humanty between Halley's one visit and the other. That must be an experience. There's
also a possibility I won't ever watch it pass by which would totally suck all
things considered. I do hope I get to witness the next visit, 62 years old,
still being quirky, being even more annoying about software freedom now that I
am an old geezer, more importantly still surrounded by people I love.

[fn:1] Actually the Observable Universe is about 90 Billion light years wide. It
is possible that the Universe is much bigger than that.
