#+TITLE: An Abundance of Katherines
#+date: 2020-11-16T06:46:13+05:30
#+tags[]: books
#+draft: false

My first encounter with John Green was through [[https://www.youtube.com/user/crashcourse][Crash Course]] a youtube channel
that puts out really well made educational videos on various subjects from
computer science to world history that really made learning fun for me back in
school. You could imagine my surprise when one day after finishing a book by the
name of 'The Fault in Our Stars' [TFIOS] and finding a picture of the author at
the end and going "Hey! I know this guy from somewhere!" and another second
later, "CRASH COURSE!". I like his books, some I've read some I've heard as
audiobooks. Most of his books don't have what you would call the traditional
happy ending and I was okay with that until I read 'An Abundance of Katherines'.
As I was nearing the end of the book, I couldn't help but felt a little unease
because everything so far was good and when that's the case in tragic stories it
means that in the next few pages lie an impending doom that is going to deliver
equal if not greater amounts of pain for every drop of happiness the few pages
before it had delivered. I was almost sure someone was going to die
and mentally preparing myself for each scenario. But the nobody did, for once
John Green gave me a happy ending. A happy ending filled with gratitude of the
past, joy of the present and hope for the future.

This book to this day remains to be one of my most favourite work of John
Green.

The story revolves around Collin Singleton who is your average sheltered child
of the 21^{st} century. But unlike most kids he exclusively dates girls named
Katherine. He was a child prodigy and like many kids that were 'above average'
as kids was struggling to maintain the status as he grew older. He struggles
with the idea that he was maybe not that special and that he may never be or
feel special ever again. So a typical nerd so obsessed on winning that he forgot
to live and cherish the moments that he had. In fact at one point his friend
Hassan points out that the reason why he keeps getting dumped might have
something to do with his insecurity of being dumped by a Katherine.

Collin like most young people fears the future and in it's uncertainty. At the
beginning of the story we see him in a quest to build a formula that will let
him predict who will dump and will get dumped in a relationship or in short
predict the future. In the end we see him realize that the uncertainty of the
future is something that makes living so exciting, we see him embrace the
uncertainty and run head first to see what the future holds for him.

Hassan his friend like Collin is also comfortable with the uncertainty of
future but his reaction however was to not confront it and in a way run away
from it. In the end we also see him confront his fears and decides to go to
college.

Lindsey is a bit interesting. In the beginning we see her clutch on to the what
she had in Gutshot and refusing to pursue anything outside the town because
according to her she was content with what she had there. In the end
we see her realize that what we humans hold on to as very important could be
taken away from us so easily and unwarranted and that sometimes some things
aren't as great as we make them up to be. In such a scenario it would only be
foolish to not wish for something more.

I think it helps us readers to think of our lives too. Are we too obsessed on
achieving that we forget to live? Are we too scared of the uncertainties that
we refuse to move forward? Are we scared of stepping outside the shell's we
built for ourselves? It's a good book that will leave you with a smile when you
turn the last page. Definitely would recommend.
