#+TITLE: "GNU/Linux Journey"
#+date: 2020-08-09T23:38:49+05:30
#+tags[]: gnu/linux experience distro free-software
#+draft: false

** The beginning
I've had my share of distro hoping in the past few years. Like most people I began my journey with Ubuntu on a then quite old laptop. It had a Pentium processor with a 2GB RAM and 128 GB hard drive. Being old it worked surprisingly well with GNU/Linux. Infact the experience was better than what I had with windows which encouraged me to make the switch and I've never looked back. Not saying GNU/Linux never had it's quirks but the overall experience was so satisfying and empowering that I didn't wanna go back to windows. Even when I bought a machine with good hardware I stuck with Tux.

** Way too many options
As I said earlier my first distro was Ubuntu then it did a bunch of Desktop Environment hopping and I did that for a while. Unity even though at first was quite bad eventually grew on me. I spent quite a bit of time on Unity. It was at this point that I figured the user experience varied from distro to distro and so began my Distro Hoping. I first hopped to Mint, then back to Ubuntu but this time it was Ubuntu's gnome flavour and stayed a bit with it but then moved to Kubuntu. tried this new project called Elementary OS but couldn't stay in it because it wasn't customizable enough for my taste. Then I moved to Solus, then Manjaro and Fedora which I sort of liked very much until the size of their updates became ridiculous and the 6 month life cycle didn't really sit well with me. I struggled to find an Operating System that I felt home at.
** Linux Sucks, I turned to the dark side.
Most of them, even the ones which were 'LTS' had nasty bugs in them and some even had broken packages and wouldn't play well with other components of your desktop. At this point I started looking for distributions that provided proper integration. That's how I came to KDE Neon, and it worked well for me for a while. I got in pretty deep into the Qt ecosystem, most the apps I used were Qt based and I was starting to settle down. I wasn't exactly happy but things worked so I just stayed with neon for a while. At this point i3 started gaining attention and so I decieded to give i3 a try. First I replaced Plasma's windows manager with i3, it worked but was very buggy and I figured I'll just use i3. I spent quite a bit of time and configured i3 the way I wanted. At this point I got intrigued by the new software Gnome was putting out and tried Fedora again and as usual I liked the experience and left the distribution later on for the same reason I left it before. At this point I turned my attention to a corner that I sort of avoided becuase I felt it was a bit too much, also because that was all that was there to try. Archlinux. i got the ISO, made a live USB and when through the whole installation process and good lord did I enjoy it. The dark side was to tempting. I absolutely enjoyed my time with Archlinux. I used i3 and had a back up DE just in case someone else had to use the system. I tried Sway and BSPWM at this point and was sort of happy with the whole experience.
** Finding true love.
At this point I came into contact with the Debian Community. It lead me to giving Debian another chance. In the past I sort of turned a blind eye towards Debian because it had not so up to date software. I really did care about having the bleeding edge software. But this point in my life I used Emacs for a lot of stuff and it had it's own package manager and everything, there wasn't anything too exciting happening in the browser space that you had to have the latest version of firefox. I wasn't exactly dazzled by every shiny new feature, sometimes I was but not as much as I did earlier in my life because I understood that most of the features we over hyped and didn't really add to the user experience. So I tried Debian, I installed it and installed Gnome on it (just went with a safe bet) and installed and setup Emacs and started using it on a daily basis. Everything just worked in a distro for once. No weird bugs. No piling RAM issues. No weird crashes. It felt nice. I decieded to stay longer and instalesd and setup my i3 config. The experience still was solid. So I went ahead and installed i3 gaps from source. Still good. At this point I started using Snaps and flatpaks. They did give me some trouble but that was mostly their issue rather than Debian's. I decieded to give myself a reality check later on and tried Arch again and that was an eye openner. I was so used to things just working on Debian that even the smallest bugs on Arch annoyed me and honestly I missed the debian ecosystem. I prefer pacman to apt, but I like features like being able to get the source of any package with a command. I switched back to Debian again. Right now I almost exclusively use Debian. I did install Ubuntu for my friends because i felt they would prefer newer software over Debian's stability. I can't recommend Debian enough and that's where I am now.
