#+TITLE: Privacy in Digital Age
#+date: 2020-11-26T12:41:54+05:30
#+tags[]: privacy

* A fun question.
What's the most efficient way to make someone behave themselves? Fear?
Torture? Money? Or maybe just let them know that they're being watched.
We humans wear masks, a ton of them and depending how comfortable we are, we
start to remove them one by one. It's not wrong to say that you are truly
yourself only in front of your conscience. We think differently depending on
where we are, we perceive and process information differently based on where we
are and we act differently depending on where we are. This is why it's important
for humans to have safe spaces where they can think and form thoughts **freely**.
This is why privacy is important in a human society.
* How much of you is actually you?
Without the privacy of our homes or our friendship circles or a closed room we
can never act or think freely, we would conform ourselves to what we've been
told is right and acceptable. Imagine a society where your every action is being
monitored, where the people watching you can predict your next move before you
even make it, where even a closed room can't provide you privacy, where you have
to live your entire lives behind masks, what sort of a society would that be?
What sort of humans would we be able to see? What sort of thoughts would they
have? More importantly how many of those thoughts would be their **own**?
Privacy is inevitable and a pre-requisite for freedom of speech and freedom of
choice. Ironically freedom of choice is the argument people often use to
rationalize and justify choices that take away their freedom.
* The celebrated salesman.
We are inching closer each day towards a future of complete surveillance. People
share all sorts of data today to corporations, everything from the last time you
searched for condoms to the last time you searched for abortion clinics.
Everything logged meticulously all for the sake of showing you fun stuff
you'd be into buying. Imagine if this was actually an actual salesman trying to
find the most intimate details of your life so that they could know the perfect
timing to approach you with the perfect product in the most perfect manner so
that they can be sure that you'll definitely buy what they're selling. What
would you think of someone who makes a company out of this? Would you use their
products? Would you celebrate them as a society? Would you put their branding on
your devices?

This is the present. Selling yourself to make your life a little bit more
convenient. To put simply people can't see the privacy they loose but they can
see the money they loose. Guess what people end up choosing. Yeah.

You should value your privacy. Please value it. Make responsible choices so that
we ourselves and generations after us can retain their free will and freedom of
choice. **You** matter and **your** choices matter.
* You Matter.
You matter and so does your choices. The one percent always have enslaved common
folks by telling them they won't matter and their choices wont matter. The
"clever ones" today like to preach this too for some reason. I can't say this
enough, we matter! Our lives matter! Our stories matter! So does our privacy.
I can never understand how a human who is capable of thought can give up on privacy.
The consequence of zero privacy is humanity being reduced to cattle. What
feature is comparable to you becoming nothing more than a cattle. It is however,
true that cattle tend to have a convenient life. Those who never move will
never notice their chains.

* Addendum
** Tip of an iceberg.
Every government is only is only a few signatures away from getting access to
your private thoughts that you've noted down in your computer or anything about
yourself that you'd like to keep to yourself. Every large corporation is only
one acquisition away from getting access to such data. How can we live with the
knowledge that if someone wished to they could end our life as we know it today.
Oh wait we have a clever trick to deal with that, box it up, throw it far away
and never think about it. Information is power. It wouldn't be stretch to
imagine an authoritarian/totalitarian government in a lot of countries the way
the political landscape is today. Imagine the power such a government would have
over it's citizens. This has never been possible before in the entire human
history.
** Enter Machines.
Mothers are special people. They know how you feel from the way you sound over a
phone call. Well they've been seeing you almost constantly from your birth. They
also use this incredible amount of information to tell you exactly the right to
make you do exactly what they want. Imagine this but if it wasn't a person but
a machine and neither the machine nor the people controlling it cared about your
well being. Collecting data and selling it for ads is one thing but using that
data to create technologies powered by AI and machine learning that knows how to
manipulate a person is entirely different. This is something that's already
around us. Widespread adoption of such practices would mean the end of free
speech and freedom of choice as we know it.
